name: Publish docker image as package

on:
  workflow_run:
    workflows: [Setup and build packages]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The build workflows have passed'
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The build workflows have failed'

  publish-docker-image:
    needs: on-success 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
          run: |
            docker build . --tag ghcr.io/0Unkn0wn/3s-api-docker:latest
            docker run ghcr.io/0Unkn0wn/3s-api-docker:latest
            docker push ghcr.io/0Unkn0wn/3s-api-docker:latest
