name: Publish docker image as package

on:
  workflow_run:
    workflows: [Setup and build packages]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The build workflows have passed'
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The build workflows have failed'

  publish-docker-image:
    needs: on-success 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GH container registry
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Cleanup system
        run: |
          docker image prune

      - name: Build Docker image
        run: |
          docker build --no-cache . -t ghcr.io/0Unkn0wn/3s-api-docker:latest

      - name: Publish image
        run: |
          docker push ghcr.io/0Unkn0wn/3s-api-docker:latest
