name: Publish docker image as GitHub package

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GH container registry
        uses: docker/login-action@v1

      - name: Cleanup system
        run: |
          docker image prune

      - name: Build Docker image
        run: |
          docker build --no-cache . -t ghcr.io/0Unkn0wn/3s-api-docker:latest

      - name: Publish image
        run: |
          docker push ghcr.io/0Unkn0wn/3s-api-docker:latest
